# Configuración de la base de datos
database:
  default_driver: mysql
  drivers:
    mysql: 
      host: localhost
      user: eltimonl_user
      pass: mayamon360
      name: eltimonl_bd
      port: default
      socket: default
    sqlite3:
      file: '___ROOT___Ocrend/Kernel/Database/Drivers/Sqlite/db.sqlite3'
      
# Configuración de servidor SMTP
mailer:
  host: eltimonlibreria.com 
  user: admin@eltimonlibreria.com
  pass: Admin-2020
  port: 465
  logo: 'vistas/img/plantilla/logotipo.png'

# Configuración de twig
twig:
  cache: false
  compiled_dir: ./app/templates/.compiled/
  charset: UTF-8
  strict_variables: false
  autoescape: html
  
# Configuración del sitio
build:
  production: false
  name: El Timón Librería
  url: https://eltimonlibreria.com/admin/
  urlAssetsPagina: https://eltimonlibreria.com/
  timezone: America/Mexico_City
  version: 3.0.1

# Configuración de cookies
sessions:
  lifetime: 86400
  user_cookie:
    enable: true
    key_encrypt: 4VDhj7UhrTbNNVWukW3Hxb6jGTnBvXNvES4ZHvp8
    lifetime: 86400

# Configuración de la api
api:
  active: true
  origin: https://eltimonlibreria.com

# Configuración de ruta
router:
  ssl: true
  path: eltimonlibreria.com/admin/